/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import config.Database;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
/**
 *
 * @author darwisy
 */
public class DataPetugasMedis extends javax.swing.JFrame {
    private Connection conn =new Database().connect();
    private DefaultTableModel model;
    /**
     * Creates new form DataObat
     */
    public DataPetugasMedis() {
        initComponents();
        
        // Initialize profesi combo box
        profesiPetugas.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] {"Dokter", "Perawat", "Bidan", "Apoteker"}));

        // Initialize status combo box
        statusPetugas.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] {"Aktif", "Non-Aktif", "Cuti", "Keluar"}));
    
        // Initialize gender radio buttons
        ButtonGroup genderGroup = new ButtonGroup();
        genderGroup.add(jkL);
        genderGroup.add(jkP);
        jkL.setSelected(true);
    
        initTable();
        loadData();
        clearForm();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetugas = new javax.swing.JTable();
        btnBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kdPetugas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nikPetugas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namaPetugas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nohpPetugas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        profesiPetugas = new javax.swing.JComboBox<>();
        jkP = new javax.swing.JRadioButton();
        jkL = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatPetugas = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        statusPetugas = new javax.swing.JComboBox<>();
        tglLahir = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(56, 182, 255));

        tblPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPetugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPetugas);

        btnBatal.setBackground(new java.awt.Color(51, 51, 51));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.setBorder(null);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("KODE PETUGAS");

        kdPetugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kdPetugas.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("DATA PETUGAS MEDIS");

        nikPetugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nikPetugas.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NIK");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("NAMA PETUGAS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("PROFESI");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("JENIS KELAMIN");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("ALAMAT");

        namaPetugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaPetugas.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("NO. HP");

        nohpPetugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nohpPetugas.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("TANGGAL LAHIR");

        btnKembali.setBackground(new java.awt.Color(48, 222, 135));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setBorder(null);
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(48, 222, 135));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 204, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(null);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setText("Search...");
        txtSearch.setBorder(null);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        profesiPetugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        profesiPetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jkP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jkP.setText("P");
        jkP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkPActionPerformed(evt);
            }
        });

        jkL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jkL.setText("L");
        jkL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkLActionPerformed(evt);
            }
        });

        alamatPetugas.setColumns(20);
        alamatPetugas.setRows(5);
        jScrollPane2.setViewportView(alamatPetugas);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("STATUS");

        statusPetugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusPetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusPetugasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nikPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kdPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(profesiPetugas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(namaPetugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jkL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jkP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(nohpPetugas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusPetugas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(97, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(kdPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nikPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(profesiPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jkL)
                            .addComponent(jkP)
                            .addComponent(jLabel6))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nohpPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        clearForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editData();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPetugasMouseClicked
        int row = tblPetugas.getSelectedRow();
    
    if (row >= 0) {
        // Fill the form fields
        kdPetugas.setText(tblPetugas.getValueAt(row, 0).toString());
        nikPetugas.setText(tblPetugas.getValueAt(row, 1).toString());
        namaPetugas.setText(tblPetugas.getValueAt(row, 2).toString());
        
        // Set profesi
        String profesi = tblPetugas.getValueAt(row, 3).toString();
        profesiPetugas.setSelectedItem(profesi);
        
        // Set gender
        String jk = tblPetugas.getValueAt(row, 4).toString();
        if (jk.equals("L")) {
            jkL.setSelected(true);
        } else {
            jkP.setSelected(true);
        }
        
        alamatPetugas.setText(tblPetugas.getValueAt(row, 5).toString());
        nohpPetugas.setText(tblPetugas.getValueAt(row, 6).toString());
        
        // Handle date
        Object dateValue = tblPetugas.getValueAt(row, 7);
        if (dateValue != null) {
            if (dateValue instanceof java.sql.Date) {
                tglLahir.setDate(((java.sql.Date) dateValue).toLocalDate());
            } else if (dateValue instanceof String) {
                try {
                    java.time.LocalDate localDate = java.time.LocalDate.parse(dateValue.toString());
                    tglLahir.setDate(localDate);
                } catch (Exception ex) {
                    tglLahir.setDate(null);
                }
            }
        } else {
            tglLahir.setDate(null);
        }
        
        // Set status
        String status = tblPetugas.getValueAt(row, 8).toString();
        statusPetugas.setSelectedItem(status);
        
        // Make kdPetugas non-editable when editing
        kdPetugas.setEditable(false);
        kdPetugas.setBackground(Color.LIGHT_GRAY);
    }
    }//GEN-LAST:event_tblPetugasMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        searchData();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        this.dispose();
    
    
    new Menu().setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void jkPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkPActionPerformed

    private void jkLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkLActionPerformed

    private void statusPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusPetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPetugasMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPetugasMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPetugasMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPetugasMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPetugasMedis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatPetugas;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jkL;
    private javax.swing.JRadioButton jkP;
    private javax.swing.JTextField kdPetugas;
    private javax.swing.JTextField namaPetugas;
    private javax.swing.JTextField nikPetugas;
    private javax.swing.JTextField nohpPetugas;
    private javax.swing.JComboBox<String> profesiPetugas;
    private javax.swing.JComboBox<String> statusPetugas;
    private javax.swing.JTable tblPetugas;
    private com.github.lgooddatepicker.components.DatePicker tglLahir;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
    model = new DefaultTableModel();
    model.addColumn("Kode Petugas");
    model.addColumn("NIK");
    model.addColumn("Nama Petugas");
    model.addColumn("Profesi");
    model.addColumn("Jenis Kelamin");
    model.addColumn("Alamat");
    model.addColumn("No. HP");
    model.addColumn("Tanggal Lahir");
    model.addColumn("Status");
    tblPetugas.setModel(model);
}
    
    
    private void loadData() {
    model.setRowCount(0);
    String sql = "SELECT * FROM petugas_medis";
    
    try (PreparedStatement stmt = conn.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("kd_petugas"),
                rs.getString("nik"),
                rs.getString("nama_petugas"),
                rs.getString("profesi"),
                rs.getString("jenis_kelamin"),
                rs.getString("alamat"),
                rs.getString("no_hp"),
                rs.getDate("tanggal_lahir"),
                rs.getString("status_akhir")
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
}
    
    private void simpanData() {
    String sql = "INSERT INTO petugas_medis (kd_petugas, nik, nama_petugas, profesi, jenis_kelamin, "
               + "alamat, no_hp, tanggal_lahir, status_akhir) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, kdPetugas.getText());
        stmt.setString(2, nikPetugas.getText());
        stmt.setString(3, namaPetugas.getText());
        stmt.setString(4, profesiPetugas.getSelectedItem().toString());
        
        // Handle gender selection
        String jenisKelamin = jkL.isSelected() ? "L" : "P";
        stmt.setString(5, jenisKelamin);
        
        stmt.setString(6, alamatPetugas.getText());
        stmt.setString(7, nohpPetugas.getText());
        
       
        // Fixed date handling
        java.time.LocalDate localDate = tglLahir.getDate();
        if (localDate != null) {
            stmt.setDate(8, java.sql.Date.valueOf(localDate));
        } else {
            stmt.setNull(8, Types.DATE);
        }
        
        stmt.setString(9, statusPetugas.getSelectedItem().toString());
        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
        loadData();
        clearForm();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
}
   
    private void editData() {
    if (kdPetugas.getText().isEmpty() || nikPetugas.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Kode Petugas dan NIK harus diisi", 
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "UPDATE petugas_medis SET nik=?, nama_petugas=?, profesi=?, jenis_kelamin=?, "
               + "alamat=?, no_hp=?, tanggal_lahir=?, status_akhir=? WHERE kd_petugas=?";
    
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, nikPetugas.getText());
        stmt.setString(2, namaPetugas.getText());
        stmt.setString(3, profesiPetugas.getSelectedItem().toString());
        
        // Handle gender selection
        String jenisKelamin = jkL.isSelected() ? "L" : "P";
        stmt.setString(4, jenisKelamin);
        
        stmt.setString(5, alamatPetugas.getText());
        stmt.setString(6, nohpPetugas.getText());
        
        // Handle birth date
       java.time.LocalDate localDate = tglLahir.getDate();
        if (localDate != null) {
            stmt.setDate(7, java.sql.Date.valueOf(localDate));
        } else {
            stmt.setNull(7, Types.DATE);
        }
        
        stmt.setString(8, statusPetugas.getSelectedItem().toString());
        stmt.setString(9, kdPetugas.getText());
        
        int updatedRows = stmt.executeUpdate();
        if (updatedRows > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
            loadData();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan", 
                "Error", JOptionPane.WARNING_MESSAGE);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
}
    
    private void hapusData() {
    int selectedRow = tblPetugas.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus");
        return;
    }
    
    // Show confirmation dialog
    int response = JOptionPane.showConfirmDialog(
        this, 
        "Anda yakin ingin menghapus data ini?", 
        "Konfirmasi Hapus",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    
    // If user clicks No, cancel the deletion
    if (response != JOptionPane.YES_OPTION) {
        return;
    }
    
    String kodePetugas = tblPetugas.getValueAt(selectedRow, 0).toString();
    String sql = "DELETE FROM petugas_medis WHERE kd_petugas=?";
    
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, kodePetugas);
        int rowsAffected = stmt.executeUpdate();
        
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
            loadData();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal dihapus");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Error: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void clearForm() {
    kdPetugas.setText(generateKodePetugas());
    nikPetugas.setText("");
    namaPetugas.setText("");
    profesiPetugas.setSelectedIndex(0);
    jkL.setSelected(true);
    alamatPetugas.setText("");
    nohpPetugas.setText("");
    tglLahir.setDate(null);
    statusPetugas.setSelectedIndex(0);
    
    kdPetugas.setEditable(true);
    kdPetugas.setBackground(Color.WHITE);
    tblPetugas.clearSelection();
}
    private void searchData() {
    String keyword = txtSearch.getText().trim();
    model.setRowCount(0);
    
    String sql = "SELECT * FROM petugas_medis WHERE "
            + "kd_petugas LIKE ? OR "
            + "nik LIKE ? OR "
            + "nama_petugas LIKE ? OR "
            + "profesi LIKE ? OR "
            + "no_hp LIKE ?";
    
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        String searchPattern = "%" + keyword + "%";
        for (int i = 1; i <= 5; i++) {
            stmt.setString(i, searchPattern);
        }
        
        ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("kd_petugas"),
                rs.getString("nik"),
                rs.getString("nama_petugas"),
                rs.getString("profesi"),
                rs.getString("jenis_kelamin"),
                rs.getString("alamat"),
                rs.getString("no_hp"),
                rs.getDate("tanggal_lahir"),
                rs.getString("status_akhir")
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Error saat mencari data: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
}
    
    private String generateKodePetugas() {
    String prefix = "PTG";
    String sql = "SELECT MAX(kd_petugas) AS last_code FROM petugas_medis WHERE kd_petugas LIKE ?";
    
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, prefix + "%");
        ResultSet rs = stmt.executeQuery();
        
        if (rs.next()) {
            String lastCode = rs.getString("last_code");
            if (lastCode != null) {
                int lastNumber = Integer.parseInt(lastCode.substring(prefix.length()));
                return prefix + String.format("%04d", lastNumber + 1);
            }
        }
    } catch (SQLException | NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, 
            "Error generating code: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    return prefix + "0001";
}
}
